import Head from 'next/head'
import Link from 'next/link'
import { SiInstagram, SiTiktok } from 'react-icons/Si'

export default function navbar() {

    return (

        <>

            <Head>
                <title>The Girl Who Talks Too Much Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className="w-full m-0 p-0 bg-cover bg-bottom" style={{ height: '60vh', maxHeight: '460px' }}>
                <div className="container max-w-4xl mx-auto pt-16 md:pt-32 text-center break-normal">
                
                    <p className="text-white font-extrabold text-3xl md:text-5xl lg:text-6xl">
                The Girl Who Talks Too Much
                    </p>
                    <p className="text-xl md:text-2xl text-gray-500">From the 808</p>
                </div>

                <nav className="mt-4 w-full max-w-5xl mx-auto">
                    <div className="container mx-auto flex items-center">
                    
                    <div className="flex w-1/2 pl-4 text-md">
                        <ul className="list-reset flex justify-between flex-1 md:flex-none items-center">
                        <li className="mr-2">
                        <Link href='/' className="inline-block py-2 px-2 text-gray-600 no-underline hover:text-gray-400">HOME</Link>
                        </li>
                        <li className="mr-2">
                        <Link className="inline-block text-gray-600 no-underline hover:text-gray-400 py-2 px-2" href="/posts/all">POSTS</Link>
                        </li>
                        <li className="mr-2">
                        <Link className="inline-block text-gray-600 no-underline hover:text-gray-400 py-2 px-2" href="#">LINK</Link>
                        </li>
                        <li className="mr-2">
                        <Link className="inline-block text-gray-600 no-underline hover:text-gray-400 py-2 px-2" href="post_vue.html">POST_VUE</Link>
                        </li>
                        </ul>
                    </div>


                    <div className="flex w-1/2 justify-end content-center">		
                        <a className="inline-block text-gray-600 no-underline hover:text-gray-400 text-center h-10 p-2 md:h-auto md:p-4 avatar" data-tippy-content="@twitter_handle" href="https://twitter.com/intent/tweet?url=#">
                        <SiInstagram size={24}/>
                        </a>
                        <a className="inline-block text-gray-600 no-underline hover:text-gray-400 text-center h-10 p-2 md:h-auto md:p-4 avatar" data-tippy-content="#facebook_id" href="https://www.facebook.com/sharer/sharer.php?u=#">
                        <SiTiktok size={24}/>
                        </a>
                    </div>

                    </div>
                </nav>
            </div>
        </>

    )
}